FROM ubuntu:18.04

MAINTAINER Branden Codd "coddb@sou.edu"

RUN apt-get update -y
RUN apt-get install -y python-pip

COPY . /app

WORKDIR /app

RUN pip install -r requirements.txt

ENTRYPOINT ["python"]

CMD ["app.py"]
